# Configuration for SemaDB, this reflects the default configuration
debug: false
# Root directory refers to the start of the filesystem where all data is stored
rootDir: /tmp/semadb
# Maximum size of shards in bytes
maxShardSize: 268435456 # 2GiB
# List of known servers at the beginning
servers:
  - localhost:9898 
# RPC Parameters
rpcHost: localhost
rpcPort: 9898
rpcTimeout: 300 # seconds
# HTTP Parameters
httpHost: localhost
httpPort: 8080