# Configuration for SemaDB, this reflects the default configuration
debug: false
# Root directory refers to the start of the filesystem where all data is stored
rootDir: /tmp/semadb
# Maximum size of shards in bytes
maxShardSize: 268435456 # 2GiB
maxShardPointCount: 250000 # 250k
# Maximum number of points to search
maxSearchLimit: 75
# Shard timeout in seconds
shardTimeout: 300 # 5 minutes
# List of known servers at the beginning
servers:
  - localhost:9898 
# RPC Parameters
rpcHost: localhost
rpcPort: 9898
rpcTimeout: 300 # seconds
rpcRetries: 2
# HTTP Parameters
httpHost: localhost
httpPort: 8080
# User Plans
userPlans:
  BASIC:
    name: Basic Plan
    maxCollections: 1
    maxCollectionSize: 1073741824 # 1GiB
    maxMetadataSize: 1024 # 1KiB