# Configuration for SemaDB
debug: &GLOBAL_DEBUG true
prettyLogOutput: true
clusterNode:
  # -------------------------------
  # Root directory refers to the start of the filesystem where all data is stored
  rootDir: &ROOT_DIR ./dump/serverC
  # List of known servers at the beginning
  servers:
    - localhost:11001
    - localhost:11002
    - localhost:11003
  # -------------------------------
  # RPC Parameters
  rpcHost: localhost
  rpcDomain: ""
  rpcPort: 11003
  rpcTimeout: 300 # seconds
  rpcRetries: 2
  # -------------------------------
  # Node database parameters
  backupFrequency: 3600 # 1 hour
  backupCount: 3
  # -------------------------------
  # Maximum size of shards in bytes
  maxShardSize: 2147483648 # 2GiB
  maxShardPointCount: 250000 # 250k
  # Maximum number of points to search
  maxSearchLimit: 75
  # -------------------------------
  # Shard manager configuration
  shardManager:
    rootDir: *ROOT_DIR
    # Shard timeout in seconds
    shardTimeout: 300 # 5 minutes
# -------------------------------
httpApi:
  debug: *GLOBAL_DEBUG
  # HTTP Parameters
  httpHost: localhost
  httpPort: 8083
  enableMetrics: true
  metricsHttpHost: localhost
  metricsHttpPort: 8093
  proxySecret: ""
  whiteListIPs:
    - 127.0.0.1
  # User Plans
  userPlans:
    BASIC:
      name: Basic Plan
      maxCollections: 1
      maxCollectionPointCount: 2000000 # 2M
      maxMetadataSize: 1024 # 1KiB
      shardBackupFrequency: 3600 # 1 hour
      shardBackupCount: 2