# Configuration for SemaDB
debug: &GLOBAL_DEBUG true
clusterNode:
  # -------------------------------
  # Root directory refers to the start of the filesystem where all data is stored
  rootDir: &ROOT_DIR ./dump/serverB
  # List of known servers at the beginning
  servers:
    - localhost:11001
    - localhost:11002
    - localhost:11003
  # -------------------------------
  # RPC Parameters
  rpcHost: localhost
  rpcPort: 11002
  rpcTimeout: 300 # seconds
  rpcRetries: 2
  # -------------------------------
  # Maximum size of shards in bytes
  maxShardSize: 268435456 # 2GiB
  maxShardPointCount: 250000 # 250k
  # Maximum number of points to search
  maxSearchLimit: 75
  # -------------------------------
  # Shard manager configuration
  shardManager:
    rootDir: *ROOT_DIR
    # Shard timeout in seconds
    shardTimeout: 300 # 5 minutes
    maxShardBackupCount: 2
# -------------------------------
httpApi:
  debug: *GLOBAL_DEBUG
  # HTTP Parameters
  httpHost: localhost
  httpPort: 8082
  enableMetrics: true
  metricsHttpHost: localhost
  metricsHttpPort: 8092
  proxySecret: ""
  whiteListIPs:
    - 127.0.0.1
  # User Plans
  userPlans:
    BASIC:
      name: Basic Plan
      maxCollections: 1
      maxCollectionPointCount: 2000000 # 2M
      maxMetadataSize: 1024 # 1KiB