name: Build Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  Test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -qq -y libhdf5-dev
      - name: Format
        run: gofmt -d .
      - name: Lint
        run: go vet
      - name: Test
        run: go test -timeout 1m ./...