name: Build Binary

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

# Please refer to https://github.com/wangyoucao577/go-release-action

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # We can adjust which platforms we are targeting but we mainly expect
        # linux/amd64 to be the default
        goos: [linux]
        goarch: [amd64] #, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.23"
          extra_files: LICENSE README.md