name: Build Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -qq -y libhdf5-dev
      - name: Test
        run: go test -v ./...